### ISSUE TITLE
New API  -  enable_ui.cgi

### ISSUE THREAD

**Issue by JamesBeam** [edent/Sercomm-API#1]
This command is used to activate the administration menu on vendor modified firmwares such as Comcast Xfinity, Cox Homelife and ADT Pulse.

/adm/enable_ui.cgi
Response: OK

Tested on iCamera2 using multiple vendor firmware versions.  

Credit to Prayas Kulshrestha who used the firmware mod kit on an old RC8061 image.  I noticed a screenshot on page 6 of his guide that included this file in adm directory listing, along with some other untested commands: 

https://dl.packetstormsecurity.net/papers/general/reverse_engineering_ip_camera_firmware.pdf

**Comment by edent** [comment]
That's brilliant. Thanks James. I've added it to the main documentation.

**Comment by JamesBeam** [comment]
Please note the UI activation is temporary and will reset each time the camera is power cycled. 

Credit to Johnny Cakes:

https://shkspr.mobi/blog/2013/11/hacking-around-with-network-cameras/#comment-5773
