### ISSUE TITLE
Full command list

### ISSUE THREAD

**Issue by nightfire37** [edent/Sercomm-API#10]
I was searching on around on the web and while digging up some information I happen to find that the FCC keeps all the information for the API. Below is a link to one of the cameras I happen to own that lists out SMB protocals but I need some sort of way to unlock it. Not an issue per say, just more information gathering.

https://fccid.io/P27OC810X/Users-Manual/User-manual-1527271

**Comment by edent** [comment]
Thanks. Is there anything in there that isn't in our documentation?

**Comment by nightfire37** [comment]
I am not sure to be honest. I was merely glossing through it.
