### ISSUE TITLE
URLs for streams

### ISSUE THREAD

**Issue by ryanbuiltthat** [edent/Sercomm-API#11]
Are there different URLs for different streams? My Sercomm camera can put out 4 different streams at once. Does anyone know how to grab a specific stream? Say you had streams 1 & 2 set to MJPEG, one 1280x720 and the other 360x240, and you wanted to only grab the smaller one?

**** UPDATE *****

It appears you can adjust your URL to get a specific stream by adding a `channel` querystring variable. For example, let's say my camera is streaming two MJPEG streams with the above mentioned sizes. 
x
`http://CAMERA-IP/img/video.mjpeg?channel=1` gives me the `1280x720`
`http://CAMERA-IP/img/video.mjpeg?channel=2` gives me the `360x240`

Obviously adjust the URL to fit what you have for the camera IP and the streaming settings. Hope this helps!

**Comment by edent** [comment]
This is documented at https://github.com/edent/Sercomm-API#video-streams

If you'd like to make the documentation clearer - please dive in :-)
