### ISSUE TITLE
Setting wpa_ascii value

### ISSUE THREAD

**Issue by tokenwizard** [edent/Sercomm-API#13]
Has anyone successfully set their camera up for Wifi with WPA2 PSK? I tried setting the mode to "9" for WPA2 PSK but it said "Invalid WEP"

I set it to "2" for WPA/WPA2 PSK and it returns "OK"

I then try to set the wpa_ascii value like:
`curl --basic --user {admin_user}:{admin_pass} "http://{ip_of_cam}/adm/set_group.cgi?group=WIRELESS&wpa_ascii=12345678"`
and it returns "OK"

But when I pull the config with:
`curl --basic --user {admin_user}:{admin_pass} "http://192.168.7.21/adm/get_group.cgi?group=WIRELESS"` the wpa_ascii item shows blank.

**Comment by edent** [comment]
I don't think the response actually shows the password. This is for security.

Does your camera connect?

**Comment by tokenwizard** [comment]
No, it does not.
That makes sense, though. I was hoping to use that Wireless Group to verify it took my SSID and Passphrase correctly since there are specific characters in the Passphrase.

I changed my Passphrase to exclude special characters and tried setting the camera to the simpler Passphrase but it still doesn't connect.

**Comment by tokenwizard** [comment]
My next thought was that I needed to make sure "connection_mode=0" to allow it to use Wired if available then if not, use WiFi.

But trying to set that with 
`curl --basic --user {admin_user}:{admin_pass} "http://{ip_of_camera}/adm/set_group.cgi?group=WIRELESS&connection_mode=0"`
fails with "ERROR"

I also notice that connection_mode key does not show up when you "get" the WIRELESS group settings:
[WIRELESS]
wlan_type=1
wlan_essid={redacted}
wlan_channel=11
wlan_domain=12
wlan_security=2
wep_authtype=1
wep_mode=1
wep_index=1
wep_ascii=
wep_kep1=
wep_kep2=
wep_kep3=
wep_kep4=
wpa_ascii=
wmm=0
iNIC=0
pin_code={redacted}


Does anyone have any documentation on the "wep_" options? Maybe those need to all be set to a "disabled" status to get it to use the WPA2 settings?

**Comment by tokenwizard** [comment]
Ok, to confirm....
I left the camera sitting for a few hours while I ran some errands, and when I cam back, it had connected to the WiFi network. 

So maybe it just take a while to switch over.
