### ISSUE TITLE
HTTP Trigger API

### ISSUE THREAD

**Issue by djr4488** [edent/Sercomm-API#2]
Not sure if this is available on all the cameras;

But the iControl iCamera-1000 model has an http_trigger.cgi which allows for something external to trigger the camera to capture video/audio.

The usage as I know it so far is;
Send a GET request to the camera at /adm/http_trigger.cgi
You need to include an Authorization header in the form of;

```
Authorization: Basic admin:password
```
Where the admin:password is the cameras admin user and admin password and is Base64 encoded.

**Comment by mknwebsolutions** [comment]
Works on Xfinity cameras - nice find!
